# Generated by Django 6.0.3 on 2026-03-31 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),  # Пример общих зависимостей, у вас могут быть свои
        ('contenttypes', '0001_initial'),
        # ('cabinet', '0001_initial'),  # <<< Эта строка УДАЛЕНА
        # Удалите здесь любые другие строки, ссылающиеся на 'cabinet'
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок поста')),
                ('text', models.TextField(verbose_name='Текст сообщения / Подпись к фото')),
                ('media_file', models.FileField(blank=True, help_text='Загрузите файл напрямую. Если есть файл, он будет отправлен с текстом сообщения.', null=True, upload_to='post_media/', verbose_name='Медиафайл (фото/видео)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('monday', models.BooleanField(default=False, verbose_name='Пн')),
                ('tuesday', models.BooleanField(default=False, verbose_name='Вт')),
                ('wednesday', models.BooleanField(default=False, verbose_name='Ср')),
                ('thursday', models.BooleanField(default=False, verbose_name='Чт')),
                ('friday', models.BooleanField(default=False, verbose_name='Пт')),
                ('saturday', models.BooleanField(default=False, verbose_name='Сб')),
                ('sunday', models.BooleanField(default=False, verbose_name='Вс')),
                ('post_time', models.TimeField(verbose_name='Время публикации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включить расписание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company', verbose_name='Инстанс (Аккаунт)')),
            ],
            options={
                'verbose_name': 'Рекламный пост',
                'verbose_name_plural': 'Рекламные посты',
            },
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=255, verbose_name='ID конкретной группы')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('autopost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.autopost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Лог публикации',
                'verbose_name_plural': 'Логи публикаций',
            },
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название списка групп')),
                ('platform', models.CharField(choices=[('wa', 'Обычный WhatsApp'), ('max', 'MAX (Green API)'), ('tg', 'Telegram (Green API)')], default='wa', max_length=20, verbose_name='Тип сети')),
                ('invite_links', models.TextField(blank=True, help_text='Вставьте ссылки (каждая с новой строки): t.me/..., max.ru/join/... или chat.whatsapp.com/...', verbose_name='Ссылки-приглашения')),
                ('identifiers', models.TextField(blank=True, help_text="Заполняется автоматически после нажатия кнопки 'Вступить'.", verbose_name='Готовые Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company', verbose_name='Инстанс (Аккаунт)')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Списки групп',
            },
        ),
        migrations.AddField(
            model_name='autopost',
            name='targets',
            field=models.ManyToManyField(to='publisher.socialgroup', verbose_name='Списки для публикации'),
        ),
    ]
    