# Generated by Django 6.0.3 on 2026-04-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0008_alter_company_options_alter_knowledgebase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='Ключ кнопки (Button key)')),
                ('label', models.CharField(max_length=255, verbose_name='Текст кнопки (Label)')),
                ('action_type', models.CharField(max_length=100, verbose_name='Тип действия (Action type)')),
                ('payload', models.TextField(blank=True, null=True, verbose_name='Пейлоад (Payload JSON)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.company', verbose_name='Компания (Company)')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя шаблона (Template name)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание (Description)')),
                ('required_inputs', models.TextField(blank=True, null=True, verbose_name='Поля ввода (required inputs JSON)')),
                ('template_code', models.TextField(blank=True, null=True, verbose_name='Код/формула (Template code)')),
                ('ui_steps', models.TextField(blank=True, null=True, verbose_name='UI шаги (UI steps JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано (Created)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.company', verbose_name='Компания (Company)')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Менеджер/Врач (Manager / Doctor)')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон (Phone)')),
                ('last_visit', models.DateField(blank=True, null=True, verbose_name='Дата последнего визита (Last visit)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='История / Заметки (History / Notes)')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='cabinet.patient', verbose_name='Пациент (Patient)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул (SKU)')),
                ('name', models.CharField(max_length=255, verbose_name='Название (Name)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание (Description)')),
                ('attributes_json', models.TextField(blank=True, null=True, verbose_name='Характеристики (Attributes JSON)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена розн. (Retail price)')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена опт. (Wholesale price)')),
                ('stock_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Остаток (Stock)')),
                ('measure_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ед. изм. (Unit)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес (kg)')),
                ('length_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Длина (m)')),
                ('width_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Ширина (m)')),
                ('height_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Высота (m)')),
                ('shipping_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Доставка за км (shipping per km)')),
                ('image', models.FileField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение (Image)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано (Created)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено (Updated)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.company', verbose_name='Компания (Company)')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.TextField(blank=True, null=True, verbose_name='Вводные данные (Inputs JSON)')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат (Result JSON)')),
                ('file', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='Файл КП (Proposal file)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано (Created)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.patient', verbose_name='Клиент (Client)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.company', verbose_name='Компания (Company)')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_tool.calculationtemplate', verbose_name='Шаблон (Template)')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата (Date)')),
                ('doctor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Врач/Менеджер (Doctor/Manager)')),
                ('procedure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Процедура / Товар (Procedure / Product)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (Price)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки (Notes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано (Created)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.company', verbose_name='Компания (Company)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='cabinet.patient', verbose_name='Пациент (Patient)')),
            ],
        ),
    ]
