# Generated by Django 6.0.3 on 2026-03-09 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании/клиники')),
                ('green_api_id', models.CharField(max_length=100, verbose_name='Green API Instance ID')),
                ('green_api_token', models.CharField(max_length=255, verbose_name='Green API Token')),
                ('gemini_key', models.CharField(max_length=255, verbose_name='Google ChatGPT Key (AI)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Сервис оплачен/активен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец (аккаунт)')),
            ],
            options={
                'verbose_name': 'Компания-клиент',
                'verbose_name_plural': '0. Компании-клиенты',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('next_contact', models.DateField(blank=True, null=True, verbose_name='Дата контакта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='cabinet.company')),
            ],
            options={
                'verbose_name': 'Клиент базы',
                'verbose_name_plural': '1. ЦРМ База',
            },
        ),
        migrations.CreateModel(
            name='DialogLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': '3. Диалоги (История)',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема (Цены, Врачи, Реанимация)')),
                ('information', models.TextField(verbose_name='Текстовые данные для ИИ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='cabinet.company')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'База знаний (Инструкции)',
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Не начат', 'Не начат'), ('Отправлено', 'Отправлено'), ('Прочитано', 'Прочитано'), ('Диалог', 'Диалог'), ('ОТКАЗ', 'Отказ')], default='Не начат', max_length=50)),
                ('probability', models.CharField(blank=True, max_length=50, verbose_name='Вероятность')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.customer', verbose_name='Клиент из базы')),
            ],
            options={
                'verbose_name': 'Статус рассылки',
                'verbose_name_plural': '2. Рассылка (Контроль)',
            },
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
