# Generated by Django 6.0.3 on 2026-03-09 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_company_customer_dialoglog_knowledgebase_outreach_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='dialoglog',
            name='company',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outreach',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='gemini_key',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='probability',
        ),
        migrations.AddField(
            model_name='company',
            name='openai_key',
            field=models.CharField(default='', max_length=255, verbose_name='Ключ OpenAI/ProxyAPI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='system_prompt',
            field=models.TextField(default='Ты помощник в клинике...', verbose_name='Инструкция для ИИ (Промт)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Сервис активен'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название клиники/бизнеса'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт владельца'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='information',
            field=models.TextField(verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='topic',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('Не начат', 'Не начат'), ('Отправлено', 'Отправлено'), ('Диалог', 'Диалог'), ('ОТКАЗ', 'Отказ')], default='Не начат', max_length=50),
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('next_contact', models.DateField(blank=True, null=True, verbose_name='Дата следующего контакта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company')),
            ],
        ),
        migrations.AddField(
            model_name='outreach',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.patient'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='DialogLog',
        ),
    ]
