# Generated by Django 6.0.3 on 2026-04-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_add_is_reanimator_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='В работе', max_length=50),
        ),
    ]
