# Generated by Django 6.0.3 on 2026-03-10 08:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_remove_outreach_customer_remove_dialoglog_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'verbose_name': 'База знаний', 'verbose_name_plural': 'Базы знаний'},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={'verbose_name': 'Журнал сообщения', 'verbose_name_plural': 'Журналы сообщений'},
        ),
        migrations.AlterModelOptions(
            name='outreach',
            options={'verbose_name': 'Рассылка/Воронка', 'verbose_name_plural': 'Рассылки/Воронки'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='last_update',
        ),
        migrations.AddField(
            model_name='outreach',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outreach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('Не начат', 'Не начат'), ('Отправлено', 'Отправлено'), ('Диалог', 'Диалог'), ('ОТКАЗ', 'ОТКАЗ'), ('ИНТЕРЕС', 'ИНТЕРЕС'), ('Записан', 'Записан')], default='Не начат', max_length=50, verbose_name='Статус воронки'),
        ),
    ]
