# Generated by Django 6.0.3 on 2026-04-15 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_add_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
