# Generated by Django 6.0.3 on 2026-03-11 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_alter_company_options_alter_knowledgebase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'verbose_name': 'Журнал сообщений', 'verbose_name_plural': 'Журналы сообщений'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='company',
            name='green_api_receive_timeout',
            field=models.IntegerField(default=20, verbose_name='Таймаут получения (сек)'),
        ),
        migrations.AddField(
            model_name='company',
            name='green_api_send_timeout',
            field=models.IntegerField(default=30, verbose_name='Таймаут отправки (сек)'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='last_contact',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Green API ID Instance'),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Green API Токен'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='openai_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='OpenAI API Ключ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system_prompt',
            field=models.TextField(default='Ты умный и вежливый ассистент компании. Помогай клиентам с вопросами.', verbose_name='Системный промпт для ИИ'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='information',
            field=models.TextField(verbose_name='Информация/Ответ'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Тема/Вопрос'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('Не начат', 'Не начат'), ('Отправлено', 'Отправлено'), ('Диалог', 'Диалог'), ('ИНТЕРЕС', 'ИНТЕРЕС'), ('Записан', 'Записан'), ('ОТКАЗ', 'ОТКАЗ')], default='Не начат', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='cabinet.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
