# Generated by Django 6.0.3 on 2026-03-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_alter_messagelog_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['topic'], 'verbose_name': 'База знаний', 'verbose_name_plural': 'Базы знаний'},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['created_at'], 'verbose_name': 'Журнал сообщений', 'verbose_name_plural': 'Журналы сообщений'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрена администратором'),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_receive_timeout',
            field=models.IntegerField(default=20, help_text='Время ожидания ответа от Green API при получении уведомлений.', verbose_name='Таймаут получения Green API (сек)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_send_timeout',
            field=models.IntegerField(default=30, help_text='Время ожидания ответа от Green API при отправке сообщений.', verbose_name='Таймаут отправки Green API (сек)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system_prompt',
            field=models.TextField(default='Ты умный и вежливый ассистент компании. Помогай клиентам с вопросами, опираясь на базу знаний.', verbose_name='Системный промпт для ИИ'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='chat_id',
            field=models.CharField(max_length=100, verbose_name='ID Чата'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='sender',
            field=models.CharField(max_length=50, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='last_contact',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний контакт'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('Не начат', 'Не начат'), ('Отправлено', 'Отправлено'), ('Диалог', 'Диалог'), ('ИНТЕРЕС', 'ИНТЕРЕС'), ('Записан', 'Записан'), ('ОТКАЗ', 'ОТКАЗ')], default='Не начат', max_length=20, verbose_name='Статус воронки'),
        ),
    ]
