# Generated by Django 6.0.3 on 2026-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_alter_knowledgebase_options_alter_messagelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vk_access_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='VK Access Token'),
        ),
        migrations.AddField(
            model_name='company',
            name='vk_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия VK токена'),
        ),
        migrations.AddField(
            model_name='company',
            name='vk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK ID пользователя'),
        ),
    ]
