# Generated by Django 6.0.3 on 2026-03-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_company_vk_access_token_company_vk_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Инстанс (Настройка API)', 'verbose_name_plural': 'Инстансы (Настройки API)'},
        ),
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outreach',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveField(
            model_name='company',
            name='green_api_receive_timeout',
        ),
        migrations.RemoveField(
            model_name='company',
            name='green_api_send_timeout',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vk_access_token',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vk_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vk_user_id',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='information',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='company',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='last_contact',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_contact',
        ),
        migrations.AddField(
            model_name='company',
            name='green_api_url',
            field=models.URLField(blank=True, default='https://api.green-api.com', help_text='Система сама подставит нужный URL в зависимости от типа сети.', null=True, verbose_name='API URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='instance_type',
            field=models.CharField(choices=[('wa', 'Обычный WhatsApp'), ('max', 'MAX (Выделенный канал)'), ('tg', 'Telegram (через Green API)')], default='wa', max_length=10, verbose_name='Тип сети / Инстанса'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.patient'),
        ),
        migrations.AddField(
            model_name='outreach',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_contact',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Green API ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Green API Token'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='openai_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI API Key'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Системный промпт (Инструкция для ИИ)'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='sender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.company'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
