# Generated by Django 6.0.3 on 2026-04-11 10:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_alter_company_options_alter_knowledgebase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.RenameField(
            model_name='outreach',
            old_name='prompt',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='company',
            name='green_api_url',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title',
            field=models.CharField(default='Без заголовка', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='outreach',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outreach',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='green_api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instance_type',
            field=models.CharField(choices=[('trial', 'Пробный'), ('pro', 'Профессиональный'), ('business', 'Бизнес')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Новая компания', max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='openai_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='cabinet.company'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='sender',
            field=models.CharField(default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='cabinet.company'),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='name',
            field=models.CharField(default='Без названия', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='cabinet.company'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний контакт'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='staff', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
